window.NovaCartCatalog = [
  {
    sku: "NV-EB-01",
    name: "Pulse Buds",
    price: 79,
    category: "audio",
    spec: "24 h case · IPX4 · Bluetooth 5.3",
    blurb: "All-day wireless earbuds for trains, calls and the walk between them. Mid-range drivers, not studio monitors.",
    page: "pulse-buds.html",
    image: "pulse-buds.svg",
    badge: "Bestseller",
    rating: 4.6,
    reviews: 1284,
  },
  {
    sku: "NV-EB-02",
    name: "Pulse Buds Pro",
    price: 129,
    category: "audio",
    spec: "ANC · 30 h case · wireless charge",
    blurb: "The same commute, quieter. Active noise cancelling and a wireless-charge case.",
    image: "pulse-pro.svg",
    rating: 4.7,
    reviews: 412,
  },
  {
    sku: "NV-EB-CASE",
    name: "Pulse replacement case",
    price: 19,
    category: "audio",
    spec: "Fits Pulse Buds · USB-C",
    blurb: "Lost the case on the Thalys. This one ships with a USB-C cable.",
    image: "pulse-case.svg",
    rating: 4.4,
    reviews: 96,
  },
  {
    sku: "NV-CH-30",
    name: "Volt USB-C 30W",
    price: 29,
    category: "charge",
    spec: "GaN · EU plug · USB-C PD",
    blurb: "One charger for phone and earbuds. Compact GaN brick, common-charger ready.",
    page: "volt-charger.html",
    image: "volt-charger.svg",
    badge: "EU plug",
    rating: 4.5,
    reviews: 890,
  },
  {
    sku: "NV-CH-65",
    name: "Volt USB-C 65W",
    price: 49,
    category: "charge",
    spec: "GaN · laptop-ready · EU plug",
    blurb: "65 W for a 14-inch laptop and a phone on the same desk.",
    image: "volt-65.svg",
    rating: 4.5,
    reviews: 301,
  },
  {
    sku: "NV-CB-02",
    name: "Drift cable 2-pack",
    price: 14,
    category: "charge",
    spec: "USB-C to C · 1 m · 60 W",
    blurb: "Two braided cables. One for the bag, one for the socket you always forget.",
    image: "drift-cable.svg",
    rating: 4.3,
    reviews: 540,
  },
  {
    sku: "NV-PL-02",
    name: "Nest Plug",
    price: 24,
    category: "home",
    spec: "Wi-Fi · energy monitor · EU",
    blurb: "A smart plug with a basic watt readout. Schedule the lamp, not the whole house.",
    page: "nest-plug.html",
    image: "nest-plug.svg",
    rating: 4.2,
    reviews: 673,
  },
  {
    sku: "NV-PL-TW",
    name: "Nest Plug twin pack",
    price: 42,
    category: "home",
    spec: "2 × Nest Plug · save €6",
    blurb: "Two plugs, one order. Desk lamp and the kettle that boils itself at 7:10.",
    image: "nest-twin.svg",
    badge: "Bundle",
    rating: 4.3,
    reviews: 188,
  },
  {
    sku: "NV-PB-10",
    name: "Halo 10 000 mAh",
    price: 59,
    category: "charge",
    spec: "USB-C in/out · 22.5 W · pack-safe",
    blurb: "A day of delay at Charleroi, still with battery left.",
    image: "halo-bank.svg",
    rating: 4.4,
    reviews: 257,
  },
  {
    sku: "NV-HUB-7",
    name: "Arc USB-C hub",
    price: 45,
    category: "carry",
    spec: "HDMI 4K · SD · 2 × USB-A · PD pass-through",
    blurb: "The dongle that lives in the sleeve pocket. One cable back to the laptop.",
    image: "arc-hub.svg",
    rating: 4.1,
    reviews: 143,
  },
  {
    sku: "NV-SL-13",
    name: "Loft Sleeve 13″",
    price: 35,
    category: "carry",
    spec: "13–14″ laptops · recycled felt",
    blurb: "A felt sleeve that takes a 14-inch laptop and a charger without turning into a tote.",
    page: "loft-sleeve.html",
    image: "loft-sleeve.svg",
    rating: 4.5,
    reviews: 219,
  },
  {
    sku: "NV-SL-16",
    name: "Loft Sleeve 16″",
    price: 39,
    category: "carry",
    spec: "15–16″ laptops · recycled felt",
    blurb: "Same sleeve, larger cut. Fits the 16-inch work machine.",
    image: "loft-16.svg",
    rating: 4.4,
    reviews: 87,
  },
];
